# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('seat_type', models.SmallIntegerField(choices=[(1, 'Bar Stool'), (2, 'Window Seat'), (3, 'Snug')], default=1)),
                ('reserved_start_time', models.DateTimeField()),
                ('reserved_end_time', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Denied')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation')),
            ],
        ),
    ]
