# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_start_time',
            field=models.TimeField(),
        ),
    ]
