# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pints', 'Pints'), ('Bottles and Cans', 'Bottles and Cans'), ('Soft Drinks', 'Soft Drinks'), ('Cocktails', 'Cocktails'), ('Spirits', 'Spirits'), ('Food', 'Food')], default='Pints', max_length=20),
        ),
    ]
