# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'PINTS'), (2, 'Bottles'), (3, 'Soft-drinks'), (4, 'Cocktails'), (5, 'Sprints')], default=1),
        ),
    ]
